name: Checks

on: [push, workflow_dispatch, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22.x
      - run: npm ci --legacy-peer-deps
      - run: npm run build
      - run: npm run test:sources -- --ci
      - uses: codecov/codecov-action@v5
        with:
          directory: ./coverage/
          fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.txt
          token: ${{ secrets.CODECOV_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
      - run: npm ci --legacy-peer-deps
      - run: npm run lint
